name: gcmarl

channels:
  - conda-forge

dependencies:
  - python=3.10
  - jax=0.4.25
  - scipy==1.12.0
  - mujoco==3.1.2
  - scikit-image==0.22.0
  - flax=0.8.3
  - chex=0.1.86
  - brax==0.10.1
  - dm-haiku==0.0.11
  - six=1.16.0
  - statsmodels==0.14.1
  - pyinstrument=4.6.2
  - matplotlib=3.8.4
  - cuda-nvcc
  - cudnn
  - pip
  - pip:
      - nvidia-cudnn-cu12==8.9.7.29
      - mujoco-mjx==3.1.2
      - stack-data==0.6.3
      - jaxlib==0.4.25+cuda12.cudnn89
      - gymnax==0.0.6
      - tyro
      - wandb==0.17.9
      - wandb_osh==1.2.2
      - mediapy==1.2.2
      - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
